auth:
  gateway:
    url: ${auth.gateway.uri:http://localhost:9080/auth-service}
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      skipPattern: org.springframework.cloud.netflix.hystrix.stream.HystrixStreamTask
    sampler:
        percentage: 1
  cloud:
    stream:
      kafka:
        binder:
           headers:
            - X-B3-TraceId
            - X-B3-SpanId
            - X-B3-Sampled
            - X-B3-ParentSpanId
            - X-Span-Name
            - X-Process-Id
management:
  security:
    enabled: false

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: kafka
          brokers: kafka
          headers:
            - X-B3-TraceId
            - X-B3-SpanId
            - X-B3-Sampled
            - X-B3-ParentSpanId
            - X-Span-Name
            - X-Process-Id
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://registry-server:8761/eureka/
