server:
  port: ${port:9081}
spring:
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
    username: authdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
security:
  oauth2:
    client:
      client-id: authclientid
      client-secret: authsecret
  basic:
    enabled: false
auth:
  cert:
    filePath: classpath:authcert.jks
    password: sopra*
    certAlias: authcert
  token:
    accessValiditySeconds: 1800
    refreshValidityMinutes: 180
api:
  title: AuthService REST API
  description: OAuth2 authentication service mocking API Gateway
  version: 1.0.0
  termsOfServiceUrl: https://github.com/SopraSteriaGroup/initiatives_backend
  license: MIT
  licenseUrl: https://tldrlegal.com/license/mit-license