server:
  port: ${port:8280}
spring:
  mail:
    host: someHost
  datasource:
    url: jdbc:h2:mem:sopridees;DB_CLOSE_DELAY=-1
    username: sopridees
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
api:
  docs:
    title: SoprIdees service REST API
    description: Documentation de l'API REST exposée par le service de gestion des SoprIdées
    version: 1.0.0
    termsOfServiceUrl: https://github.com/SopraSteriaGroup/initiatives_backend
    license: MIT
    licenseUrl: https://tldrlegal.com/license/mit-license
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: initiatives_app
      client-secret: initiatives_super_secure_secret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA04oHvREfP2YxamN5CcwasVsJe1N0Kg5THUaziTLEBESU9zXT2OiMQEtPCOmgS8ophZd/eYUK8CIaYVnGafZdE0snKalpPPKeAlp5bKuwgTRQl6galArMm53I7sjgZjcDRu8MGX1/OW9yZJRapBXdyFCnQlEJrZJLIuesqNmpV8NsUDs0gHYu4GuuWNwB+jRrOagoSNHgSZqpi2dJBmZjCNvycqNAwy2qRRl16Pb5MxeuBV+6O5ObwqrxcFFTa0waBHz3wmPbDc75JrN3KQXT3Flj7FBbZdIOX4gornPgJ+phw/aQcYVEdqbmzpCibkf9y66QFIQgN4jaNeTyonVwvwIDAQAB
          -----END PUBLIC KEY-----